# -*- coding: utf-8 -*-
"""Text_Generation_LangChain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Vv1RHK3IkSMvHpk8BmpmYMj0IlzGiXe
"""

!pip install transformers==4.36.2 accelerate==0.25.0 sentencepiece

!pip install torch --index-url https://download.pytorch.org/whl/cpu

!pip install langchain==0.1.17 langchain-core==0.1.52 langchain-community==0.0.36

!pip install huggingface_hub

import warnings
warnings.filterwarnings("ignore")

import os
os.environ["HUGGINGFACEHUB_API_TOKEN"] = input("Enter your Hugging Face API Key: ")

import torch
from transformers import pipeline

from langchain_community.llms import HuggingFacePipeline
from langchain.chains import LLMChain
from langchain.prompts import PromptTemplate

model_name = "google/flan-t5-large"  # You can change to flan-t5-xl

hf_pipeline = pipeline(
    task="text2text-generation",
    model=model_name,
    device=-1  # CPU only
)

# Adjust generation parameters
hf_pipeline.model.generation_config.max_new_tokens = 512
hf_pipeline.model.generation_config.temperature = 0.7
hf_pipeline.model.generation_config.do_sample = True

# Wrap in LangChain interface
llm = HuggingFacePipeline(pipeline=hf_pipeline)

template = """
Question: {question}

Answer: Let's think step by step.
"""

prompt = PromptTemplate(
    template=template,
    input_variables=["question"]
)

llm_chain = LLMChain(llm=llm, prompt=prompt)

# Question 1
question1 = "Explain the concept of black holes in simple terms."
answer1 = llm_chain.invoke({"question": question1})
print("Answer 1:\n", answer1["text"], "\n")

# Question 2
question2 = "Explain key principles in generative models and their data generation process."
answer2 = llm_chain.invoke({"question": question2})
print("Answer 2:\n", answer2["text"], "\n")

# Question 2
question3 = " Explain the role of transfer learning in enhancing generative model."
answer3 = llm_chain.invoke({"question": question3})
print("Answer 3:\n", answer3["text"], "\n")